name: screen_capturer_example
description: "Demonstrates how to use the screen_capturer plugin."
publish_to: "none"

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  bot_toast: ^4.1.3
  flutter:
    sdk: flutter
  path_provider: ^2.0.15
  preference_list: ^0.0.1
  screen_capturer:
    # When depending on this package from a real application you should use:
    #   screen_capturer: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  shell_executor: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mostly_reasonable_lints: ^0.1.1

flutter:
  uses-material-design: true
