name: screen_capturer_platform_interface
description: A common platform interface for the screen_capturer plugin.
version: 0.2.2
homepage: https://github.com/leanflutter/screen_capturer/blob/main/packages/screen_capturer_platform_interface

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.0
  mostly_reasonable_lints: ^0.1.2
